spring:
  application:
    name: api-stock
  datasource:
    url: jdbc:postgresql://localhost:5432/stock
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8050

management:
  endpoints:
    web:
      exposure:
        include:
          - healt
          - mappings

---
spring:
  application:
    name: api-stock
  profile:
    prod
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/stock
    username: postgres
    password: postgres
